name: Github Pages
on:
  workflow_dispatch:
    inputs:
      jos:
        required: true
        type: choice
        options: ['prod', 'test', 'beta', 'betalnt', 'all']
  push:
    branches: ['dev','main']

jobs:
  release:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0
      - name: Install dependencies & build
        env:
          VITE_ENV: 'prod'
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Deploy Gh-Pages ðŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DK_PROD }}
          publish_dir: ./dist
          external_repository: zoofiio/zoofi-ui
          cname: zoofi.io
  test:
    if: contains(github.event.head_commit.message, '[test]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0
      - name: Install dependencies & build
        env:
          VITE_ENV: 'prod'
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Deploy Gh-Pages ðŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DK_TEST }}
          publish_dir: ./dist
          external_repository: zoofiio/zoofi-ui-site-test
          cname: test.zoofi.io
